### ISSUE TITLE
Integration tests might be needed

### ISSUE THREAD

**Issue by Killerqu00** [NyagiByte/Compression#47]
With the amount of complexity we are having in this modpack, there needs to be some way to verify that new changes don't break something. 
Ideally, that should also verify that no softlocks in progression occur, but the key word is ideally - this might be too hard to implement in a way that doesn't require tons of manual upkeep, which is NOT something integration tests should do.

Potential changes:

- [ ] No crash test - check that game launches without crashing and ~~preferably before the heat death of the universe~~ not too long
- [ ] LMFT test - check that Load My Fucking Tags doesn't report any tags that are broken
- [ ] KJS test - same as above but with KJS errors/warnings
- [ ] Progression test (?) - check the lack of softlocks somehow

**Comment by NyagiByte** [comment]
The no crash and kubejs test just sorta naturally come during deving so i'm not sure making a point of those makes sense. For the LMFT we might just have to do a binary search to see what mod is unhappy. As for progression test i'm not sure how that would be automatable, i mostly rely on the early access group to help with that

**Comment by Killerqu00** [comment]
> The no crash and kubejs test just sorta naturally come during deving so i'm not sure making a point of those makes sense. 

kind of, but it still helps to see on a PR, for example

> For the LMFT we might just have to do a binary search to see what mod is unhappy. 

LMFT logs the broken tags, you just need to check where we use them and why they broke

> As for progression test i'm not sure how that would be automatable, i mostly rely on the early access group to help with that

still thinking on it, but with exponential modpack scaling I doubt manual testing will be viable as an option to check the _whole_ progression tree
